apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: cd
spec:
  service:
    type: NodePort
  users:
    - name: cd
      databases:
        - cd
      options: "SUPERUSER"
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-14.3-3.2-0
  postgresVersion: 14
  instances:
    - name: instance1
      replicas: 1
      resources:
        requests:
          memory: 8Gi
          cpu: 2.0
        limits:
          memory: 8Gi
          cpu: 2.0
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1000Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-0
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 100Gi
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          # preload
          shared_preload_libraries: "pg_stat_statements"
          pg_stat_statements.track: "all"
          # custom
          statement_timeout: "300s"
          max_locks_per_transaction: 1024
          synchronous_commit: "off"
          jit: "off"
          log_min_duration_statement: "30s"
          # generated, https://pgtune.leopard.in.ua/
          max_connections: 40
          shared_buffers: 2GB
          effective_cache_size: 6GB
          maintenance_work_mem: 1GB
          checkpoint_completion_target: 0.9
          wal_buffers: 16MB
          default_statistics_target: 500
          random_page_cost: 1.1
          effective_io_concurrency: 300
          work_mem: 13107kB
          min_wal_size: 4GB
          max_wal_size: 16GB
          max_worker_processes: 4
          max_parallel_workers_per_gather: 2
          max_parallel_workers: 4
          max_parallel_maintenance_workers: 2
